"""add_priority_and_tags

Revision ID: 6d12ddf8f27b
Revises: None
Create Date: 2026-01-15 15:47:33.860770

"""
from typing import Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d12ddf8f27b'
down_revision: Union[str, None] = None
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('order', sa.Integer(), server_default='0', nullable=False))
    op.add_column('todos', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'display_name')
    op.drop_column('todos', 'tags')
    op.drop_column('todos', 'priority')
    op.drop_column('todos', 'order')
    # ### end Alembic commands ###
